// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("body_urban_civ_female_a");
	self attach("head_urban_civ_female_a", "", true);
	self.headModel = "head_urban_civ_female_a";
	self.voice = "seal";
}

precache()
{
	precacheModel("body_urban_civ_female_a");
	precacheModel("head_urban_civ_female_a");
}