// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("body_urban_civ_female_b");
	self attach("head_urban_civ_female_b", "", true);
	self.headModel = "head_urban_civ_female_b";
	self.voice = "seal";
}

precache()
{
	precacheModel("body_urban_civ_female_b");
	precacheModel("head_urban_civ_female_b");
}